#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
    ckAnimation generator by FeelinVoids.
    https://github.com/FeelinVoids/ckAnimation-generator
"""

from typing import Type
from . import algorithms
import os
import shutil

FILE_EXT = ".ckAnimation"
DESCRIPTION = "File generated by ckAnimation_generator\nhttps://github.com/FeelinVoids/ckAnimation-generator"

def main():
    print("Enter the file name. (Skip - standard algorithm name)")
    filepath = input("Filename > ")

    print("\nSelect the algorithm:")
    for i, alg in enumerate(algorithms._registeredAlgorithms):
        print(str(i) + " - " + alg.getName(alg))

    algNum = 0
    try:
        algNum = int(input("number > "))
    except:
        algNum = 0

    alg: Type[algorithms.AlgorithmBase] = algorithms._registeredAlgorithms[algNum]()
    print("\nStarting algorithm " + alg.getName())

    if alg.getParams() != {}:
        print("This algorithm has some settings:")

    for k in alg.getParams().keys():
        alg.setParamValue(k, input(f" - {alg.getParamDisplayname(k)} > "))

    alg.start()

    filename = alg.getName()+FILE_EXT

    if filepath == "":
        filepath = os.path.join(os.getcwd(), filename)
    elif not filepath.endswith(FILE_EXT):
        filepath += FILE_EXT

    filepath = os.path.abspath(filepath)

    frameStrings = []
    print("Generating...")
    for frame in alg.frames:
        num = frame.number+1
        tmpstr = "\n    <Frame"+str(num)+">\
                    \n        <ColorPicture>"

        for button in frame.buttons:
            tmpstr += button.rgb2hex()
            if button.number != algorithms.KEY_COUNT-1:
                tmpstr += ","

        tmpstr += "\n        </ColorPicture>\
                    \n        <DisplayTime>"+str(frame.displayTime)+"</DisplayTime>\
                    \n    </Frame"+str(num)+">"

        frameStrings.append(tmpstr)

    startString = "<Root>\
                    \n    <Description>"+DESCRIPTION+"</Description>\
                    \n    <Time>0</Time>\
                    \n    <BackgroundColor>000000</BackgroundColor>\
                    \n    <FrameCount>"+str(alg.frameCount-1)+"</FrameCount>"

    endString = "\n</Root>"

    print("Done.\n")

    f = open(filepath, "w")
    f.write(startString)
    for i in range(alg.frameCount):
        f.write(frameStrings[i])
    f.write(endString)
    f.close()

    print("File saved as", filepath)
    print("Import it into KeyDominator2 in the RGB Animation tab.")

if __name__ == "__main__":
    main()
